# Generated by Django 4.2 on 2023-05-01 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Magazines",
        ),
    ]
